let people = [
  {
    name: "Travis Liu",
    age: 22,
    gender: "Male",
    race: "Asian",
    exes: 23,
    image: "images/Travis Liu.jpg",
    catchphrase:
      "They call me Mr. Right... because I’m always swiped that way.",
  },
  {
    name: "Tiffiany",
    age: 19,
    gender: "Female",
    race: "Asian",
    exes: 15,
    image: "images/Tiffiany.jpg",
    catchphrase: "I promise I’m more fun than your ex’s Netflix account!",
  },
  {
    name: "Travis Tam",
    age: 25,
    gender: "Male",
    race: "Asian",
    exes: 7,
    image: "images/Travis Tam.jpg",
    catchphrase: "I’m not like your last swipe, I’m better!",
  },
  {
    name: "Erica",
    age: 20,
    gender: "Female",
    race: "Asian",
    exes: 9,
    image: "images/Erica.jpg",
    catchphrase: "Let’s make our first date so good, your ex gets jealous.",
  },
  {
    name: "Terrance",
    age: 23,
    gender: "Male",
    race: "Asian",
    exes: 5,
    image: "images/Terrance Wong.jpg",
    catchphrase: "Warning: I’ll like your dog more than you!",
  },
  {
    name: "Kevin Ngyuen",
    age: 26,
    gender: "Male",
    race: "Asian",
    exes: 12,
    image: "images/Kevin Ngyuen.jpg",
    catchphrase: "Swipe right, and I’ll Venmo you for boba!",
  },

  {
    name: "Aang",
    age: 12,
    gender: "Male",
    race: "Asian",
    exes: 923,
    image: "images/Aang.jpg",
    catchphrase: "I’ll sweep you off your feet faster than Appa!",
  },
  {
    name: "Eric Ou",
    age: 20,
    gender: "Male",
    race: "Asian",
    exes: 11,
    image: "images/Eric Ou.jpg",
    catchphrase: "I’m the OU-tlier you’ve been looking for.",
  },
  {
    name: "Henry Lin",
    age: 25,
    gender: "Male",
    race: "Asian",
    exes: 6,
    image: "images/Henry Lin.jpg",
    catchphrase: "I’m here for a good time, not a long text thread.",
  },
  {
    name: "Jennifer",
    age: 22,
    gender: "Female",
    race: "Asian",
    exes: 3,
    image: "images/Jennifer.jpg",
    catchphrase: "Texting me back isn’t hard. Dating me is even easier.",
  },
  {
    name: "Serena",
    age: 21,
    gender: "Female",
    race: "Asian",
    exes: 18,
    image: "images/Serena.jpg",
    catchphrase: "I’m the main character in this love story.",
  },
  {
    name: "Dylan Jiang",
    age: 15,
    gender: "Male",
    race: "Asian",
    exes: -2,
    image: "images/Dylan.jpeg",
    catchphrase: "My eyes may be small, but my heart is big for you.",
  },
  {
    name: "Tyrone",
    age: 23,
    gender: "Male",
    race: "Black",
    exes: 678,
    image: "images/tyrone.jpg",
    catchphrase: "678 exes, but I’m looking for that one.",
  },
  {
    name: "Jaquavius",
    age: 24,
    gender: "Male",
    race: "Black",
    exes: 6,
    image: "images/jaquavius.jpg",
    catchphrase: "I might just be your next favorite mistake.",
  },
  {
    name: "Tiana",
    age: 18,
    gender: "Female",
    race: "Black",
    exes: 8,
    image: "images/tiana.jfif",
    catchphrase: "Swipe right if you’re ready to meet royalty.",
  },
  {
    name: "Chanel",
    age: 30,
    gender: "Female",
    race: "Black",
    exes: 2,
    image: "images/chanel.jfif",
    catchphrase: "I’m expensive, but my love is priceless.",
  },
  {
    name: "Hombre",
    age: 59,
    gender: "Male",
    race: "Latina",
    exes: 75,
    image: "images/hombre.jpg",
    catchphrase: "They call me 'El Hombre,' but you can call me yours.",
  },
  {
    name: "Maria",
    age: 19,
    gender: "Female",
    race: "Latina",
    exes: 5,
    image: "images/maria.jfif",
    catchphrase: "Let’s salsa into each other’s hearts.",
  },
  {
    name: "Camila",
    age: 19,
    gender: "Female",
    race: "Latina",
    exes: 2,
    image: "images/camila.jpg",
    catchphrase: "You bring the tacos, I’ll bring the spice.",
  },
  {
    name: "Gloria",
    age: 43,
    gender: "Female",
    race: "White",
    exes: 5,
    image: "images/gloria.jpg",
    catchphrase: "I’m older, wiser, and ready for love.",
  },
  {
    name: "Gorlock The Destroyer",
    age: 20,
    gender: "Female",
    race: "Latina",
    exes: 842,
    image: "images/gorlock.jpg",
    catchphrase: "Big heart, bigger love—are you ready to handle it?",
  },
  {
    name: "Mohammed",
    age: 53,
    gender: "Male",
    race: "Middle-Eastern",
    exes: 2,
    image: "images/mohammed.jpg",
    catchphrase: "Ima blow my way into your heart.",
  },
  {
    name: "Squidgame Guy",
    age: 47,
    gender: "Male",
    race: "Asian",
    exes: 1,
    image: "images/SeongGiHun.jpg",
    catchphrase: "IVE PLAYED THESE GAMES BEFORE!",
  },
  {
    name: "Sudail",
    age: 73,
    gender: "Male",
    race: "Middle-Eastern",
    exes: 12,
    image: "images/sudail.jpg",
    catchphrase: "I love my woman like I love my kids, young and ripe.",
  },
  {
    name: "Ben",
    age: 32,
    gender: "Male",
    race: "White",
    exes: 0,
    image: "images/ben.jpg",
    catchphrase: "Just a nice guy looking for someone to talk too.",
  },
  {
    name: "Luigi",
    age: 26,
    gender: "Male",
    race: "White",
    exes: 10,
    image: "images/luigi.jfif",
    catchphrase: "I'll file a insurance claim for you.",
  },
  {
    name: "Demarcus",
    age: 34,
    gender: "Male",
    race: "White",
    exes: 5,
    image: "images/d.webp",
    catchphrase: "I have god and anime on my side.",
  },
  {
    name: "Sexy guy from squidgame",
    age: 55,
    gender: "Male",
    race: "Asian",
    exes: 2,
    image: "images/GongYoo.gif",
    catchphrase: "Do you wanna play a game?",
  },
];
export { people };
